### ISSUE TITLE
About loss processing in MaskFormerDistillation

### ISSUE THREAD

**Issue by zhengyuan-xie** [fcdl94/CoMFormer#2]
Hi, thanks for your great work! I'm trying to reproduce the results in paper and there are some problems. I run the ade.sh(task 0) mentioned in the first issue and the function __call__ of MaskFormerDistillation returns an empty dict. It seems that all losses are removed in line 182. What can I do to solve this problem? Is it reasonable to add 'else: ' before 'losses.pop(k)' and modify the weight_dict in task 0(only leave loss_ce, loss_mask and loss_dice)? Looking for your reply!

**Comment by fcdl94** [comment]
Hello! Yes, I noted this problem. I made a mistake when loading the code! You should add the else like in the original mask2former code (here: https://github.com/facebookresearch/Mask2Former/blob/9b0651c6c1d5b3af2e6da0589b719c514ec0d69a/mask2former/maskformer_model.py#L211).

I'll report it here for clarity:

```
      for k in list(losses.keys()):
          if k in self.criterion.weight_dict:
              losses[k] *= self.criterion.weight_dict[k]
         else:
              # remove this loss if not specified in `weight_dict`
              losses.pop(k)
```

I'll fix it soon. Thank you for pointing it out.

**Comment by zhengyuan-xie** [comment]
Thanks for your fast reply!
