### ISSUE TITLE
About Evaluate on VOC Pascal 2012 dataset

### ISSUE THREAD

**Issue by XihuaQiao** [fcdl94/CoMFormer#3]
Hi, thanks for your great work!
I noticed the register_voc_segm.py file in your GitHub. Have you ever tested the CoMFormer in voc datasets? How is the performance? Cause I have been using Mask2Former on voc dataset and the results are disappointing.

**Comment by fcdl94** [comment]
Hey! Yes, I tried with Pascal-VOC but I found it a bit unstable. 
I got good results, but I had to change them a bit the setting - such as removing an explicit background class and making it implicit.
Anyway, I don't remember all the details... it was a bit ago

**Comment by XihuaQiao** [comment]
OMG, thank you for replying so quickly! I have tried the Mask2Former with the incremental setting as 16-5, and the base result of VOC in semantic segmentation is really low, with mIoU-Base = 74. I think it might be because the proportion of the background class is too large and MaskFormer architecture is not effective in this kind of situation.

**Comment by fcdl94** [comment]
Take a look in some previous commits, I had some scripts on Pascal VOC and some way to train them!

**Comment by XihuaQiao** [comment]
Thanks a lot~
