### ISSUE TITLE
Checkpoint point path is missing

### ISSUE THREAD

**Issue by alcardel** [fcdl94/CoMFormer#7]
When I'm trying to run the code 
I get this error AssertionError: Checkpoint ade_ss/mya_100-50-ov/MxF/step0/model_final.pth not found!

checked the whole folder never found this model_final.pth 

please help me out by providing the checkpoints 

feel free to reach out if any further details are required

A detailed look at the error is attached below. 

![error](https://github.com/fcdl94/CoMFormer/assets/139988872/212f7d47-0361-472e-8dad-e9b9db2c7943)

**Comment by JFJ-Bin** [comment]
I also meet this problem

**Comment by JFJ-Bin** [comment]
@fcdl94 Could you tell me where is 'Checkpoint ade_ss/mya_100-50-ov/MxF/step0/model_final.pth ' Thank you!

**Comment by fcdl94** [comment]
Hey! You should train it, there's not available checkpoint.
